//! The facilitator kit, generated from the embedded curriculum - never
//! hand-maintained. Pure functions only; `thunk kit` in main.rs does the I/O.

use crate::ladder_tag;
use thunk_content::Curriculum;
use thunk_core::Check;

/// The answer as a facilitator reads it aloud: the text of the correct option
/// for Choice, the canonical accepted answer for Short/Predict, and the correct
/// sequence (joined with arrows) for Order. This renders exactly what
/// `Check::canonical_answer` grades as `Correct`.
fn answer_text(c: &Check) -> String {
    match c {
        Check::Choice {
            options, answer, ..
        } => options[*answer].clone(),
        Check::Short { answers, .. } | Check::Predict { answers, .. } => answers[0].clone(),
        Check::Order { items, .. } => items.join(" -> "),
    }
}

/// The checks of one lesson, by the `mN-NN-` id convention the whole course
/// uses: module dir `m3-bus` + lesson `02-spi` own every `m3-02-*` check.
fn lesson_checks<'a>(checks: &'a [Check], module_dir: &str, lesson_id: &str) -> Vec<&'a Check> {
    let module_n = module_dir.split('-').next().unwrap_or(module_dir);
    let lesson_n = lesson_id.split('-').next().unwrap_or(lesson_id);
    let prefix = format!("{module_n}-{lesson_n}-");
    checks
        .iter()
        .filter(|c| c.id().0.starts_with(&prefix))
        .collect()
}

/// The pacing guide: how the course is meant to move, module by module.
pub fn pacing_md() -> String {
    let mut s = String::from(
        "# thunk pacing guide\n\n\
         Generated by `thunk kit` from the curriculum built into this binary. \
         Do not edit by hand; regenerate instead. Everything here works fully \
         offline - the course needs no network at any point.\n\n\
         ## How pacing works\n\n\
         The course is self-paced and gated on mastery, not on time. A module \
         is mastered when every one of its checks has been answered correctly \
         at least once; mastering a module unlocks the next. There is no \
         penalty for wrong answers - learners retry until it sticks.\n\n",
    );
    s.push_str(&format!(
        "Learners who already know some of this material can take the \
         placement diagnostic ({} items, three checks per knowledge module). \
         Placing out of a module counts as mastery for gating, so an \
         experienced learner starts where the material is new to them.\n",
        Curriculum::placement().len()
    ));
    for m in Curriculum::all() {
        let checks = Curriculum::load_checks(&m.id.0);
        s.push_str(&format!(
            "\n## {} - {}\n\n{} lessons, {} checks.\n\n",
            ladder_tag(&m.id.0),
            m.title,
            m.lessons.len(),
            checks.len()
        ));
        for l in &m.lessons {
            let n = lesson_checks(&checks, &m.id.0, &l.id.0).len();
            s.push_str(&format!("- {} ({n} checks)\n", l.title));
        }
        s.push_str(&format!(
            "\nSuggested rhythm: one lesson and its checks per sitting - {} \
             sittings - then the module gate (every remaining check passed) \
             as the session after the last lesson.\n",
            m.lessons.len()
        ));
    }
    s
}

/// The answer key: every check with the answer that grades correct.
pub fn answer_key_md() -> String {
    let mut s = String::from(
        "# thunk answer key\n\n\
         For facilitators only - this file holds the correct answer to every \
         check in the course. Keep it out of learners' hands; the checks only \
         measure anything if the answers are earned.\n\n\
         Generated by `thunk kit` from the curriculum built into this binary. \
         Do not edit by hand; regenerate instead.\n",
    );
    for m in Curriculum::all() {
        let checks = Curriculum::load_checks(&m.id.0);
        s.push_str(&format!("\n## {} - {}\n", ladder_tag(&m.id.0), m.title));
        for l in &m.lessons {
            s.push_str(&format!("\n### {}\n\n", l.title));
            for c in lesson_checks(&checks, &m.id.0, &l.id.0) {
                s.push_str(&format!(
                    "- `{}` - {}\n  Answer: {}\n",
                    c.id().0,
                    c.prompt(),
                    answer_text(c)
                ));
                // Short and Predict both accept an alternate list; the key
                // spells them out so a facilitator can honor a learner's
                // equivalent phrasing (or byte spelling) on the spot.
                if let Check::Short { answers, .. } | Check::Predict { answers, .. } = c {
                    if answers.len() > 1 {
                        s.push_str(&format!("  Also accepted: {}\n", answers[1..].join(", ")));
                    }
                }
            }
        }
    }
    s
}

/// Per-module mastery as CSV, one row per ladder entry: what a facilitator
/// redirects to a file for record keeping. "Mastered" is exactly the gate's
/// definition - `mastered_or_placed`, the same call `ladder_state` makes.
pub fn export_csv(p: &thunk_core::Progress) -> String {
    let mut s = String::from("module,title,checks_passed,checks_total,mastered\n");
    for (m, (id, checks)) in Curriculum::all().iter().zip(Curriculum::ladder()) {
        let passed = checks
            .iter()
            .filter(|c| p.checks_passed.contains(c))
            .count();
        let mastered = if p.mastered_or_placed(&id, &checks) {
            "yes"
        } else {
            "no"
        };
        s.push_str(&format!(
            "{},{},{passed},{},{mastered}\n",
            id.0,
            csv_field(&m.title),
            checks.len()
        ));
    }
    s
}

/// Comma-safe field: module titles carry no commas today, but if one ever
/// does, quote it rather than corrupt the row.
fn csv_field(t: &str) -> String {
    if t.contains(',') {
        format!("\"{}\"", t.replace('"', "\"\""))
    } else {
        t.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_pacing_guide_covers_the_whole_ladder() {
        let md = pacing_md();
        for m in thunk_content::Curriculum::all() {
            assert!(md.contains(&m.title), "pacing guide missing {}", m.title);
        }
        assert!(
            md.contains("placement"),
            "pacing guide must explain placement"
        );
        assert!(
            !md.contains("http://") && !md.contains("https://"),
            "kit must be hermetic"
        );
    }

    #[cfg(feature = "open")]
    #[test]
    fn the_open_kit_documents_m7() {
        // On the open build the facilitator kit must cover M7 - the pacing
        // guide names it and the answer key holds every M7 answer - so a
        // facilitator running the open profile is not missing a module's key.
        let pacing = pacing_md();
        assert!(pacing.contains("M7"), "pacing guide names the M7 rung");
        assert!(pacing.contains("First Patch"), "pacing names M7's title");
        let key = answer_key_md();
        for c in thunk_content::Curriculum::load_checks("m7-first-patch") {
            assert!(key.contains(&c.id().0), "answer key missing {}", c.id().0);
            assert!(
                key.contains(answer_text(&c).trim()),
                "answer key missing the answer to {}",
                c.id().0
            );
        }
    }

    #[test]
    fn the_answer_key_carries_every_check_and_its_canonical_answer() {
        let md = answer_key_md();
        for m in thunk_content::Curriculum::all() {
            for c in thunk_content::Curriculum::load_checks(&m.id.0) {
                assert!(md.contains(&c.id().0), "answer key missing {}", c.id().0);
                // `canonical_answer()` returns the `Answer` enum - an index
                // for Choice. The key must show what a facilitator reads
                // aloud, so assert on the rendered text instead.
                assert!(
                    md.contains(answer_text(&c).trim()),
                    "answer key missing the answer to {}",
                    c.id().0
                );
                // Short checks accept alternates; the key lists them all.
                if let thunk_core::Check::Short { answers, .. } = &c {
                    for a in answers {
                        assert!(
                            md.contains(a.trim()),
                            "answer key missing alternate {a:?} for {}",
                            c.id().0
                        );
                    }
                }
            }
        }
        assert!(!md.contains("http://") && !md.contains("https://"));
    }
}
